language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t iswaran/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true iswaran/docker-react npm run test